const config = {
  APP_NAME: "theliner-ehs-gemba",
  BASE_URL: process.env.EXPO_PUBLIC_VITE_BASE_URL,
  LOCAL_PROFILE: "THELINER_EHS_GEMBA_PROFILE",
  LOCAL_AUTHENTICATED: "THELINER_EHS_GEMBA_AUTHENTICATED",
  LOCAL_ACCESS_TOKEN: "THELINER_EHS_GEMBA_ACCESS_TOKEN",
  LOCAL_REFRESH_TOKEN: "THELINER_EHS_GEMBA_REFRESH_TOKEN",
  LOCAL_LOGIN_TYPE: "THELINER_EHS_GEMBA_LOGIN_TYPE",
  TIMEOUT: 50000,
  PAGE_SIZE: 500,
  TENANT_URL: "https://htpa.sharepoint.com",
  EHS_GEMBA_SITE: "https://htpa.sharepoint.com/Projects/EHS-GEMBA",
  LAST_VERSION: "2024-04-25 17:00",
  IN_TEST: process.env.EXPO_PUBLIC_VITE_IN_TEST === "Yes",
  IGNORE_MAIL: false,
};

export default config;
